import React from 'react';
import { copyText } from "../Logic"



export const SymArrows = () => {

    return (
        <div>
            <h2>Símbolos De Flecha</h2>
            <div className="button-arrow-container">
                <button onClick={() => copyText("⬆")}>⬆</button>
                <button onClick={() => copyText("⬅")}>⬅</button>
                <button onClick={() => copyText("⮕")}>⮕</button>
                <button onClick={() => copyText("⬇")}>⬇</button>
                <button onClick={() => copyText("⬉")}>⬉</button>
                <button onClick={() => copyText("⬈")}>⬈</button>
                <button onClick={() => copyText("⬋")}>⬋</button>
                <button onClick={() => copyText("⬊")}>⬊</button>
                <button onClick={() => copyText("⬍")}>⬍</button>
                <button onClick={() => copyText("⬌")}>⬌</button>
                <button onClick={() => copyText("⭠")}>⭠</button>
                <button onClick={() => copyText("⭡")}>⭡</button>
                <button onClick={() => copyText("⭣")}>⭣</button>
                <button onClick={() => copyText("⭢")}>⭢</button>
                <button onClick={() => copyText("⭤")}>⭤</button>
                <button onClick={() => copyText("⭥")}>⭥</button>
                <button onClick={() => copyText("⮃")}>⮃</button>
                <button onClick={() => copyText("⮂")}>⮂</button>
                <button onClick={() => copyText("⮐")}>⮐</button>
                <button onClick={() => copyText("⮑")}>⮑</button>
                <button onClick={() => copyText("⬎")}>⬎</button>
                <button onClick={() => copyText("⬏")}>⬏</button>
                <button onClick={() => copyText("⬐")}>⬐</button>
                <button onClick={() => copyText("⬑")}>⬑</button>
                <button onClick={() => copyText("⬿")}>⬿</button>
                <button onClick={() => copyText("⬳")}>⬳</button>
                <button onClick={() => copyText("⬱")}>⬱</button>
                <button onClick={() => copyText("⭆")}>⭆</button>
                <button onClick={() => copyText("⭅")}>⭅</button>
                <button onClick={() => copyText("↞")}>↞</button>
                <button onClick={() => copyText("↟")}>↟</button>
                <button onClick={() => copyText("↠")}>↠</button>
                <button onClick={() => copyText("↡")}>↡</button>
                <button onClick={() => copyText("↩")}>↩</button>
                <button onClick={() => copyText("↖")}>↖</button>
                <button onClick={() => copyText("↘")}>↘</button>
                <button onClick={() => copyText("↗")}>↗</button>
                <button onClick={() => copyText("↙")}>↙</button>
                <button onClick={() => copyText("↕")}>↕</button>
                <button onClick={() => copyText("↛")}>↛</button>
                <button onClick={() => copyText("↚")}>↚</button>
                <button onClick={() => copyText("↝")}>↝</button>
                <button onClick={() => copyText("↜")}>↜</button>
                <button onClick={() => copyText("↪")}>↪</button>
                <button onClick={() => copyText("↣")}>↣</button>
                <button onClick={() => copyText("↢")}>↢</button>
                <button onClick={() => copyText("↥")}>↥</button>
                <button onClick={() => copyText("↤")}>↤</button>
                <button onClick={() => copyText("↦")}>↦</button>
                <button onClick={() => copyText("↧")}>↧</button>
                <button onClick={() => copyText("↨")}>↨</button>
                <button onClick={() => copyText("↪")}>↪</button>
                <button onClick={() => copyText("↩")}>↩</button>
                <button onClick={() => copyText("↱")}>↱</button>
                <button onClick={() => copyText("↰")}>↰</button>
                <button onClick={() => copyText("↲")}>↲</button>
                <button onClick={() => copyText("↬")}>↬</button>
                <button onClick={() => copyText("↫")}>↫</button>
                <button onClick={() => copyText("↮")}>↮</button>
                <button onClick={() => copyText("↯")}>↯</button>
                <button onClick={() => copyText("↭")}>↭</button>
                <button onClick={() => copyText("↳")}>↳</button>
                <button onClick={() => copyText("↴")}>↴</button>
                <button onClick={() => copyText("↹")}>↹</button>
                <button onClick={() => copyText("↸")}>↸</button>
                <button onClick={() => copyText("↷")}>↷</button>
                <button onClick={() => copyText("↶")}>↶</button>
                <button onClick={() => copyText("↻")}>↻</button>
                <button onClick={() => copyText("↺")}>↺</button>
                <button onClick={() => copyText("⟳")}>⟳</button>
                <button onClick={() => copyText("⟲")}>⟲</button>
                <button onClick={() => copyText("↽")}>↽</button>
                <button onClick={() => copyText("↼")}>↼</button>
                <button onClick={() => copyText("↿")}>↿</button>
                <button onClick={() => copyText("↾")}>↾</button>
                <button onClick={() => copyText("⇁")}>⇁</button>
                <button onClick={() => copyText("⇀")}>⇀</button>
                <button onClick={() => copyText("⇃")}>⇃</button>
                <button onClick={() => copyText("⇂")}>⇂</button>
                <button onClick={() => copyText("⇄")}>⇄</button>
                <button onClick={() => copyText("⇅")}>⇅</button>
                <button onClick={() => copyText("⇆")}>⇆</button>
                <button onClick={() => copyText("⇉")}>⇉</button>
                <button onClick={() => copyText("⇇")}>⇇</button>
                <button onClick={() => copyText("⇊")}>⇊</button>
                <button onClick={() => copyText("⇈")}>⇈</button>
                <button onClick={() => copyText("⇌")}>⇌</button>
                <button onClick={() => copyText("⇋")}>⇋</button>
                <button onClick={() => copyText("⇐")}>⇐</button>
                <button onClick={() => copyText("⇑")}>⇑</button>
                <button onClick={() => copyText("⇒")}>⇒</button>
                <button onClick={() => copyText("⇓")}>⇓</button>
                <button onClick={() => copyText("⇔")}>⇔</button>
                <button onClick={() => copyText("⬁")}>⬁</button>
                <button onClick={() => copyText("⬀")}>⬀</button>
                <button onClick={() => copyText("⬄")}>⬄</button>
                <button onClick={() => copyText("⬃")}>⬃</button>
                <button onClick={() => copyText("⬂")}>⬂</button>
                <button onClick={() => copyText("⇏")}>⇏</button>
                <button onClick={() => copyText("⇍")}>⇍</button>
                <button onClick={() => copyText("⇎")}>⇎</button>
                <button onClick={() => copyText("⇕")}>⇕</button>
                <button onClick={() => copyText("⇙")}>⇙</button>
                <button onClick={() => copyText("⇖")}>⇖</button>
                <button onClick={() => copyText("⇗")}>⇗</button>
                <button onClick={() => copyText("⇘")}>⇘</button>
                <button onClick={() => copyText("⇛")}>⇛</button>
                <button onClick={() => copyText("⇚")}>⇚</button>
                <button onClick={() => copyText("⇝")}>⇝</button>
                <button onClick={() => copyText("⇜")}>⇜</button>
                <button onClick={() => copyText("⇟")}>⇟</button>
                <button onClick={() => copyText("⇞")}>⇞</button>
                <button onClick={() => copyText("⇠")}>⇠</button>
                <button onClick={() => copyText("⇣")}>⇣</button>
                <button onClick={() => copyText("⇡")}>⇡</button>
                <button onClick={() => copyText("⇢")}>⇢</button>
                <button onClick={() => copyText("⇥")}>⇥</button>
                <button onClick={() => copyText("⇤")}>⇤</button>
                <button onClick={() => copyText("⇿")}>⇿</button>
                <button onClick={() => copyText("⇽")}>⇽</button>
                <button onClick={() => copyText("⇾")}>⇾</button>
                <button onClick={() => copyText("⇨")}>⇨</button>
                <button onClick={() => copyText("⇦")}>⇦</button>
                <button onClick={() => copyText("⇧")}>⇧</button>
                <button onClick={() => copyText("⇪")}>⇪</button>
                <button onClick={() => copyText("⇩")}>⇩</button>
                <button onClick={() => copyText("▶")}>▶</button>
                <button onClick={() => copyText("⌅")}>⌅</button>
                <button onClick={() => copyText("⌆")}>⌆</button>
                <button onClick={() => copyText("⌤")}>⌤</button>
                <button onClick={() => copyText("⏎")}>⏎</button>
                <button onClick={() => copyText("☇")}>☇</button>
                <button onClick={() => copyText("☈")}>☈</button>
                <button onClick={() => copyText("➔")}>➔</button>
                <button onClick={() => copyText("➘")}>➘</button>
                <button onClick={() => copyText("➙")}>➙</button>
                <button onClick={() => copyText("➚")}>➚</button>
                <button onClick={() => copyText("➛")}>➛</button>
                <button onClick={() => copyText("➜")}>➜</button>
                <button onClick={() => copyText("➝")}>➝</button>
                <button onClick={() => copyText("➞")}>➞</button>
                <button onClick={() => copyText("➟")}>➟</button>
                <button onClick={() => copyText("➠")}>➠</button>
                <button onClick={() => copyText("➡")}>➡</button>
                <button onClick={() => copyText("➢")}>➢</button>
                <button onClick={() => copyText("➣")}>➣</button>
                <button onClick={() => copyText("➤")}>➤</button>
                <button onClick={() => copyText("➥")}>➥</button>
                <button onClick={() => copyText("➦")}>➦</button>
                <button onClick={() => copyText("➧")}>➧</button>
                <button onClick={() => copyText("➨")}>➨</button>
                <button onClick={() => copyText("➪")}>➪</button>
                <button onClick={() => copyText("➩")}>➩</button>
                <button onClick={() => copyText("➬")}>➬</button>
                <button onClick={() => copyText("➫")}>➫</button>
                <button onClick={() => copyText("➮")}>➮</button>
                <button onClick={() => copyText("➭")}>➭</button>
                <button onClick={() => copyText("➱")}>➱</button>
                <button onClick={() => copyText("➯")}>➯</button>
                <button onClick={() => copyText("➲")}>➲</button>
                <button onClick={() => copyText("➴")}>➴</button>
                <button onClick={() => copyText("➳")}>➳</button>
                <button onClick={() => copyText("➵")}>➵</button>
                <button onClick={() => copyText("➷")}>➷</button>
                <button onClick={() => copyText("➶")}>➶</button>
                <button onClick={() => copyText("➹")}>➹</button>
                <button onClick={() => copyText("➸")}>➸</button>
                <button onClick={() => copyText("➻")}>➻</button>
                <button onClick={() => copyText("➺")}>➺</button>
                <button onClick={() => copyText("➽")}>➽</button>
                <button onClick={() => copyText("➼")}>➼</button>
                <button onClick={() => copyText("➾")}>➾</button>
                <button onClick={() => copyText("⤴")}>⤴</button>
                <button onClick={() => copyText("⤵")}>⤵</button>
                <button onClick={() => copyText("↵")}>↵</button>
                <button onClick={() => copyText("↓")}>↓</button>
                <button onClick={() => copyText("↔")}>↔</button>
                <button onClick={() => copyText("←")}>←</button>
                <button onClick={() => copyText("→")}>→</button>
                <button onClick={() => copyText("↑")}>↑</button>
                <button onClick={() => copyText("⍇")}>⍇</button>
                <button onClick={() => copyText("⍈")}>⍈</button>
                <button onClick={() => copyText("⍐")}>⍐</button>
                <button onClick={() => copyText("⍗")}>⍗</button>
                <button onClick={() => copyText("⇫")}>⇫</button>
                <button onClick={() => copyText("⇬")}>⇬</button>
                <button onClick={() => copyText("⇭")}>⇭</button>
                <button onClick={() => copyText("⇮")}>⇮</button>
                <button onClick={() => copyText("⇯")}>⇯</button>
                <button onClick={() => copyText("⇰")}>⇰</button>
                <button onClick={() => copyText("⇱")}>⇱</button>
                <button onClick={() => copyText("⇲")}>⇲</button>
                <button onClick={() => copyText("⇳")}>⇳</button>
                <button onClick={() => copyText("⇴")}>⇴</button>
                <button onClick={() => copyText("⇵")}>⇵</button>
                <button onClick={() => copyText("⇶")}>⇶</button>
                <button onClick={() => copyText("⇷")}>⇷</button>
                <button onClick={() => copyText("⇸")}>⇸</button>
                <button onClick={() => copyText("⇹")}>⇹</button>
                <button onClick={() => copyText("⇺")}>⇺</button>
                <button onClick={() => copyText("⇻")}>⇻</button>
                <button onClick={() => copyText("⇼")}>⇼</button>
                <button onClick={() => copyText("𖤂")}>𖤂</button>
                <button onClick={() => copyText("𖣫")}>𖣫</button>
            </div>
        </div>
    )
}


