import { copyText } from "../Logic"



export const SymLines = () => {

    return (
        <div className="buttons-container lines-container">
            <div className="buttons-title-container">
                <h2>Símbolos De Lineas</h2>
            </div>
            <div className="button-symbols-container">
                <button className="button-line" onClick={() => copyText("╱")}>╱</button>
                <button className="button-line" onClick={() => copyText("╲")}>╲</button>
                <button className="button-line" onClick={() => copyText("╳")}>╳</button>
                <button className="button-line" onClick={() => copyText("╭")}>╭</button>
                <button className="button-line" onClick={() => copyText("╮")}>╮</button>
                <button className="button-line" onClick={() => copyText("╯")}>╯</button>
                <button className="button-line" onClick={() => copyText("╰")}>╰</button>
                <button className="button-line" onClick={() => copyText("◜")}>◜</button>
                <button className="button-line" onClick={() => copyText("◝")}>◝</button>
                <button className="button-line" onClick={() => copyText("◞")}>◞</button>
                <button className="button-line" onClick={() => copyText("◟")}>◟</button>
                <button className="button-line" onClick={() => copyText("◠")}>◠</button>
                <button className="button-line" onClick={() => copyText("◡")}>◡</button>
                <button className="button-line" onClick={() => copyText("⌈")}>⌈</button>
                <button className="button-line" onClick={() => copyText("⌊")}>⌊</button>
                <button className="button-line" onClick={() => copyText("⌉")}>⌉</button>
                <button className="button-line" onClick={() => copyText("⌋")}>⌋</button>
                <button className="button-line" onClick={() => copyText("⎡")}>⎡</button>
                <button className="button-line" onClick={() => copyText("⎣")}>⎣</button>
                <button className="button-line" onClick={() => copyText("⎤")}>⎤</button>
                <button className="button-line" onClick={() => copyText("⎦")}>⎦</button>
                <button className="button-line" onClick={() => copyText("⎧")}>⎧</button>
                <button className="button-line" onClick={() => copyText("⎩")}>⎩</button>
                <button className="button-line" onClick={() => copyText("⎫")}>⎫</button>
                <button className="button-line" onClick={() => copyText("⎭")}>⎭</button>
                <button className="button-line" onClick={() => copyText("⎸")}>⎸</button>
                <button className="button-line" onClick={() => copyText("⎹")}>⎹</button>
                <button className="button-line" onClick={() => copyText("⎾")}>⎾</button>
                <button className="button-line" onClick={() => copyText("⎿")}>⎿</button>
                <button className="button-line" onClick={() => copyText("⏉")}>⏉</button>
                <button className="button-line" onClick={() => copyText("⏊")}>⏊</button>
                <button className="button-line" onClick={() => copyText("⏋")}>⏋</button>
                <button className="button-line" onClick={() => copyText("⏌")}>⏌</button>
                <button className="button-line" onClick={() => copyText("≡")}>≡</button>
                <button className="button-line" onClick={() => copyText("≣")}>≣</button>
                <button className="button-line" onClick={() => copyText("☰")}>☰</button>
                <button className="button-line" onClick={() => copyText("☱")}>☱</button>
                <button className="button-line" onClick={() => copyText("☲")}>☲</button>
                <button className="button-line" onClick={() => copyText("☳")}>☳</button>
                <button className="button-line" onClick={() => copyText("☴")}>☴</button>
                <button className="button-line" onClick={() => copyText("☵")}>☵</button>
                <button className="button-line" onClick={() => copyText("☶")}>☶</button>
                <button className="button-line" onClick={() => copyText("☷")}>☷</button>
                <button className="button-line" onClick={() => copyText("═")}>═</button>
                <button className="button-line" onClick={() => copyText("║")}>║</button>
                <button className="button-line" onClick={() => copyText("╒")}>╒</button>
                <button className="button-line" onClick={() => copyText("╓")}>╓</button>
                <button className="button-line" onClick={() => copyText("╔")}>╔</button>               
                <button className="button-line" onClick={() => copyText("╕")}>╕</button>              
                <button className="button-line" onClick={() => copyText("╖")}>╖</button>
                <button className="button-line" onClick={() => copyText("╗")}>╗</button>
                <button className="button-line" onClick={() => copyText("╘")}>╘</button>
                <button className="button-line" onClick={() => copyText("╙")}>╙</button>
                <button className="button-line" onClick={() => copyText("╚")}>╚</button>
                <button className="button-line" onClick={() => copyText("╛")}>╛</button>
                <button className="button-line" onClick={() => copyText("╜")}>╜</button>
                <button className="button-line" onClick={() => copyText("╝")}>╝</button>
                <button className="button-line" onClick={() => copyText("╞")}>╞</button>
                <button className="button-line" onClick={() => copyText("╟")}>╟</button>
                <button className="button-line" onClick={() => copyText("╠")}>╠</button>
                <button className="button-line" onClick={() => copyText("╡")}>╡</button>
                <button className="button-line" onClick={() => copyText("╢")}>╢</button>
                <button className="button-line" onClick={() => copyText("╣")}>╣</button>
                <button className="button-line" onClick={() => copyText("╤")}>╤</button>
                <button className="button-line" onClick={() => copyText("╥")}>╥</button>
                <button className="button-line" onClick={() => copyText("╦")}>╦</button>
                <button className="button-line" onClick={() => copyText("╧")}>╧</button>
                <button className="button-line" onClick={() => copyText("╨")}>╨</button>
                <button className="button-line" onClick={() => copyText("╩")}>╩</button>
                <button className="button-line" onClick={() => copyText("╪")}>╪</button>
                <button className="button-line" onClick={() => copyText("╫")}>╫</button>
                <button className="button-line" onClick={() => copyText("╬")}>╬</button>
                <button className="button-line" onClick={() => copyText("ˍ")}>ˍ</button>
                <button className="button-line" onClick={() => copyText("‐")}>‐</button>
                <button className="button-line" onClick={() => copyText("⎯")}>⎯</button>
                <button className="button-line" onClick={() => copyText("‒")}>‒</button>
                <button className="button-line" onClick={() => copyText("―")}>―</button>
                <button className="button-line" onClick={() => copyText("⎺")}>⎺</button>
                <button className="button-line" onClick={() => copyText("⎻")}>⎻</button>
                <button className="button-line" onClick={() => copyText("⎼")}>⎼</button>
                <button className="button-line" onClick={() => copyText("⎽")}>⎽</button>
                <button className="button-line" onClick={() => copyText("‗")}>‗</button>
                <button className="button-line" onClick={() => copyText("‖")}>‖</button>
                <button className="button-line" onClick={() => copyText("─")}>─</button>
                <button className="button-line" onClick={() => copyText("━")}>━</button>
                <button className="button-line" onClick={() => copyText("│")}>│</button>
                <button className="button-line" onClick={() => copyText("┃")}>┃</button>
                <button className="button-line" onClick={() => copyText("┄")}>┄</button>
                <button className="button-line" onClick={() => copyText("┅")}>┅</button>
                <button className="button-line" onClick={() => copyText("┆")}>┆</button>
                <button className="button-line" onClick={() => copyText("┇")}>┇</button>
                <button className="button-line" onClick={() => copyText("┈")}>┈</button>
                <button className="button-line" onClick={() => copyText("┉")}>┉</button>
                <button className="button-line" onClick={() => copyText("┊")}>┊</button>
                <button className="button-line" onClick={() => copyText("┋")}>┋</button>
                <button className="button-line" onClick={() => copyText("╌")}>╌</button>
                <button className="button-line" onClick={() => copyText("╍")}>╍</button>
                <button className="button-line" onClick={() => copyText("╎")}>╎</button>
                <button className="button-line" onClick={() => copyText("╴")}>╴</button>
                <button className="button-line" onClick={() => copyText("╵")}>╵</button>
                <button className="button-line" onClick={() => copyText("╶")}>╶</button>
                <button className="button-line" onClick={() => copyText("╷")}>╷</button>
                <button className="button-line" onClick={() => copyText("╸")}>╸</button>
                <button className="button-line" onClick={() => copyText("╹")}>╹</button>
                <button className="button-line" onClick={() => copyText("╺")}>╺</button>
                <button className="button-line" onClick={() => copyText("╻")}>╻</button>
                <button className="button-line" onClick={() => copyText("╼")}>╼</button>
                <button className="button-line" onClick={() => copyText("╽")}>╽</button>
                <button className="button-line" onClick={() => copyText("╾")}>╾</button>
                <button className="button-line" onClick={() => copyText("╿")}>╿</button>
                <button className="button-line" onClick={() => copyText("▏")}>▏</button>
                <button className="button-line" onClick={() => copyText("▕")}>▕</button>
                <button className="button-line" onClick={() => copyText("╏")}>╏</button>
                <button className="button-line" onClick={() => copyText("–")}>–</button>
                <button className="button-line" onClick={() => copyText("—")}>—</button>
                <button className="button-line" onClick={() => copyText("⌌")}>⌌</button>
                <button className="button-line" onClick={() => copyText("⌍")}>⌍</button>
                <button className="button-line" onClick={() => copyText("⌎")}>⌎</button>
                <button className="button-line" onClick={() => copyText("⌏")}>⌏</button>
                <button className="button-line" onClick={() => copyText("⌜")}>⌜</button>
                <button className="button-line" onClick={() => copyText("⌝")}>⌝</button>
                <button className="button-line" onClick={() => copyText("⌞")}>⌞</button>
                <button className="button-line" onClick={() => copyText("⌟")}>⌟</button>
                <button className="button-line" onClick={() => copyText("┌")}>┌</button>
                <button className="button-line" onClick={() => copyText("┍")}>┍</button>
                <button className="button-line" onClick={() => copyText("┎")}>┎</button>
                <button className="button-line" onClick={() => copyText("┏")}>┏</button>
                <button className="button-line" onClick={() => copyText("┐")}>┐</button>
                <button className="button-line" onClick={() => copyText("┑")}>┑</button>
                <button className="button-line" onClick={() => copyText("┒")}>┒</button>
                <button className="button-line" onClick={() => copyText("┓")}>┓</button>
                <button className="button-line" onClick={() => copyText("└")}>└</button>
                <button className="button-line" onClick={() => copyText("┕")}>┕</button>
                <button className="button-line" onClick={() => copyText("┖")}>┖</button>
                <button className="button-line" onClick={() => copyText("┗")}>┗</button>
                <button className="button-line" onClick={() => copyText("┘")}>┘</button>
                <button className="button-line" onClick={() => copyText("┙")}>┙</button>
                <button className="button-line" onClick={() => copyText("┚")}>┚</button>
                <button className="button-line" onClick={() => copyText("┛")}>┛</button>
                <button className="button-line" onClick={() => copyText("├")}>├</button>
                <button className="button-line" onClick={() => copyText("┝")}>┝</button>
                <button className="button-line" onClick={() => copyText("┞")}>┞</button>
                <button className="button-line" onClick={() => copyText("┟")}>┟</button>
                <button className="button-line" onClick={() => copyText("┠")}>┠</button>
                <button className="button-line" onClick={() => copyText("┡")}>┡</button>
                <button className="button-line" onClick={() => copyText("┢")}>┢</button>
                <button className="button-line" onClick={() => copyText("┣")}>┣</button>
                <button className="button-line" onClick={() => copyText("┤")}>┤</button>
                <button className="button-line" onClick={() => copyText("┥")}>┥</button>
                <button className="button-line" onClick={() => copyText("┦")}>┦</button>
                <button className="button-line" onClick={() => copyText("┧")}>┧</button>
                <button className="button-line" onClick={() => copyText("┨")}>┨</button>
                <button className="button-line" onClick={() => copyText("┩")}>┩</button>
                <button className="button-line" onClick={() => copyText("┪")}>┪</button>
                <button className="button-line" onClick={() => copyText("┫")}>┫</button>
                <button className="button-line" onClick={() => copyText("┬")}>┬</button>
                <button className="button-line" onClick={() => copyText("┭")}>┭</button>
                <button className="button-line" onClick={() => copyText("┮")}>┮</button>
                <button className="button-line" onClick={() => copyText("┯")}>┯</button>
                <button className="button-line" onClick={() => copyText("┰")}>┰</button>
                <button className="button-line" onClick={() => copyText("┱")}>┱</button>
                <button className="button-line" onClick={() => copyText("┲")}>┲</button>
                <button className="button-line" onClick={() => copyText("┳")}>┳</button>
                <button className="button-line" onClick={() => copyText("┴")}>┴</button>
                <button className="button-line" onClick={() => copyText("┵")}>┵</button>
                <button className="button-line" onClick={() => copyText("┶")}>┶</button>
                <button className="button-line" onClick={() => copyText("┷")}>┷</button>
                <button className="button-line" onClick={() => copyText("┸")}>┸</button>
                <button className="button-line" onClick={() => copyText("┹")}>┹</button>
                <button className="button-line" onClick={() => copyText("┺")}>┺</button>
                <button className="button-line" onClick={() => copyText("┻")}>┻</button>
                <button className="button-line" onClick={() => copyText("┼")}>┼</button>
                <button className="button-line" onClick={() => copyText("┽")}>┽</button>
                <button className="button-line" onClick={() => copyText("┾")}>┾</button>
                <button className="button-line" onClick={() => copyText("┿")}>┿</button>
                <button className="button-line" onClick={() => copyText("╀")}>╀</button>
                <button className="button-line" onClick={() => copyText("╁")}>╁</button>
                <button className="button-line" onClick={() => copyText("╂")}>╂</button>
                <button className="button-line" onClick={() => copyText("╃")}>╃</button>
                <button className="button-line" onClick={() => copyText("╄")}>╄</button>
                <button className="button-line" onClick={() => copyText("╅")}>╅</button>
                <button className="button-line" onClick={() => copyText("╆")}>╆</button>
                <button className="button-line" onClick={() => copyText("╇")}>╇</button>
                <button className="button-line" onClick={() => copyText("╈")}>╈</button>
                <button className="button-line" onClick={() => copyText("╉")}>╉</button>
                <button className="button-line" onClick={() => copyText("╊")}>╊</button>
                <button className="button-line" onClick={() => copyText("╋")}>╋</button>
            </div>
        </div>
    )
}